### ISSUE TITLE
Accept regexish strings

### ISSUE THREAD

**Issue by steelbrain** [es128/anymatch#10] opened 2015-09-02 12:34 UTC
I am using anymatch to ignore stuff, I often pass the ignore parameter from CLI, all those cli parameters are parsed as string. It'd be nice to have anymatch convert `/*.css/` to regex automatically.

**Comment by es128** [comment] 2015-09-02 13:21
@jonschlinkert any chance you have or know of a util that detects and converts strings to regexes in this way (including stripping the slashes from the string before converting)? Didn't find one in a quick npm search.

**Comment by jonschlinkert** [comment] 2015-09-02 15:18
you could use `micromatch.makeRe('*.css')`. that just returns a regex for the glob pattern

**Comment by steelbrain** [comment] 2015-09-02 15:20
@jonschlinkert Yep! That would work!  but I am afraid glob regex would only match `something.css` but not `directory/something.css` (unless I am misinformed about globs)

**Comment by jonschlinkert** [comment] 2015-09-02 15:26
well, you could always do `micromatch.makeRe('**/*.css')` or customize the glob to do what you need (or maybe I missed a nuance in what you need to accomplish?). you might be able to pass `cwd` as well

**Comment by es128** [comment] 2015-09-02 15:43
Globs are already supported, so yes @steelbrain you could pass `**/*.css` to meet the use case you've described. 

But I had thought that was just an over-simplified example. I'm thinking that there'd be value in auto-converting strings to regexes based on detecting that it's wrapped in slashes.

**Comment by es128** [comment] 2015-10-16 20:28
Was just thinking about this, and the problem is that there's no good way to know whether something like `/dir/ig` is intended to be a path or a regex.

The CLI tool described above should provide separate switches for strings vs regexes and do whatever it has to do to take the input for a regex and turn it into an actual `RegExp` instance before passing it into anymatch.

I'm not sure if there's a lib out there that would take a string like `'/*.css/ig'` and properly convert it into a `RegExp` to help with this use case, but it seems like something that ought to exist.

Closing the issue.

**Closed by es128** 2015-10-16 20:28 UTC
